# Exported from Render on 2025-09-09T18:26:28Z
services:
- type: web
  name: n8n
  runtime: node
  repo: https://github.com/samiskaff/n8n
  plan: free
  envVars:
  - key: WEBHOOK_URL
    sync: false
  - key: N8N_BASIC_AUTH_PASSWORD
    sync: false
  - key: N8N_BASIC_AUTH_USER
    sync: false
  - key: N8N_BASIC_AUTH_ACTIVE
    sync: false
  region: oregon
  buildCommand: pnpm install --frozen-lockfile; pnpm run build
  startCommand: pnpm run start
  autoDeployTrigger: commit
version: "1"

